version: '2'
services:
    bubux-app:
        image: bubux
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bubux-postgresql:5432/bubux
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bubux-postgresql:
        extends:
            file: postgresql.yml
            service: bubux-postgresql
